module.exports = {
	'id_invalid': 'Id invalid',
	"not_found": 'Not found',
	"unauthenticated": 'User not authenticated',
	'unauthorized': 'User not authorized',
	'not_granted': 'Not granted',
	'verify_invalid': 'This verification link is invalid!',
	'signin_failed': 'Signing in failed, please check your email and password',
	'auth_failed': 'Signing in failed, please check your auth info',
	'password_format': 'should not start or end with spacing character(s).',
	'phone_format': 'format is incorrect',
	'password_confirm_required': '^Confirm password is required.',
	'password_confirm_not_match': '^Password and confirmation do not match.',
	'user_name_length': 'must be at least 25 characters',
	'email_invalid': '^Email address is invalid, blacklisted or not available.',
	'required': 'is required',
	'file_upload_extension': 'Upload file invalid',
	'upload_fail': 'Upload file invalid',
	'upload_field': 'Upload field not found',
	"unique": "Input value is already used. Please choose another one.",
	"internal_server": "Internal server error",
	"entity_too_large": "Input data is too large",
	'agency_status_invalid': 'is either active or inactive (default is inactive)',
	"nearby_invalid": 'is invalid',
	"user_inactive": "Please contact your administrator to reactivate your account",
};
